### ISSUE TITLE
Error While Installing Setoolkit

### ISSUE THREAD

**Issue by GetRektBoy724** [termux/unstable-packages#108]
When i installing pillow it showed up this
File "/data/data/com.termux/files/usr/tmp/pip-install-jxse0yri/pillow/setup.py", line 674, in build_extensions                                                      raise RequiredDependencyException(f)              __main__.RequiredDependencyException: jpeg                                                                  During handling of the above exception, another exception occurred:                                                                                               Traceback (most recent call last):                      File "<string>", line 1, in <module>                  File "/data/data/com.termux/files/usr/tmp/pip-install-jxse0yri/pillow/setup.py", line 888, in <module>        raise RequiredDependencyException(msg)            __main__.RequiredDependencyException:                                                                       The headers or library files could not be found for jpeg,                                                   a required dependency when compiling Pillow from source.                                                                                                          Please see the install instructions at:                  https://pillow.readthedocs.io/en/latest/installation.html                                                                                                                                                            ----------------------------------------          ERROR: Command "/data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-jxse0yri/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-h8f4voua/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-jxse0yri/pillow/                dpkg: error processing package setoolkit (--configure):                                                      installed setoolkit package post-installation script subprocess returned error exit status 1               Errors were encountered while processing:              setoolkit                                            E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by GetRektBoy724** [comment]
Pliss help me fast

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/unstable-packages/commit/378f2b73fb51a30c5055e8877eec91f947b50516.

**Comment by GetRektBoy724** [comment]
Thanks for your reply
